### ISSUE TITLE
type checking returning a fun object

### ISSUE THREAD

**Issue by gomoripeti** [josefs/Gradualizer#108]
I believe these examples should pass type checking, however they fail with weird errors

```
-spec nil() -> [].
nil() -> [].

-spec return_fun() -> term().
return_fun() -> fun nil/0.

-spec return_fun2() -> fun().
return_fun2() -> fun nil/0.
```
yields
```
The function nil on line 57 is expected to return INVALID-FORM:[{type,32,bounded_fun,[{type,32,'fun',[{type,32,product,[]},{type,32,nil,[]}]},[]]}]: but it returns term()
The function nil on line 60 is expected to return INVALID-FORM:[{type,32,bounded_fun,[{type,32,'fun',[{type,32,product,[]},{type,32,nil,[]}]},[]]}]: but it returns fun()
```

both functions return `fun(() -> [])` type which is a subtype of both `term()` and `fun()`.
I suspect gradualizer currently checks the opposite (via `any_subtype`), whether `term()` or `fun()` is a subtype of `fun(() -> [])`

**Comment by josefs** [comment]
I suspect this is a problem in `expect_fun_type`.
