### ISSUE TITLE
All string literals fail for nonempty_string()

### ISSUE THREAD

**Issue by zuiderkwast** [josefs/Gradualizer#120]
When checking a string literal against a type Ty, it is checked that `string()` is a subtype of Ty. This doesn't work if `Ty = nonempty_string()`. This example gives a type error:

```Erlang
-spec foo() -> nonempty_string().
foo() -> "banana".
```
It is added as a known problem test case in 6042d29385e474037b74493621c96cf413224d05

**Comment by gomoripeti** [comment]
wow, I didn't even noticed there is such type alias as `nonempty_string` (thanks god there is no `maybe_nonempty_maybe_improper_string` and friends :) )
