### ISSUE TITLE
Checking of map expression against bigger type

### ISSUE THREAD

**Issue by UlfNorell** [josefs/Gradualizer#131]
```erlang
-spec f() -> #{ a := b } | undefined.
f() -> #{ a => b }
%% The map on line 3 does not have type #{a := b} | undefined
```
The problem is this check
https://github.com/josefs/Gradualizer/blob/9ce38f1828202eaa27fa471e6ed799be5acbbd9f/src/typechecker.erl#L2013-L2014
that requires `ResTy` to be a subtype of `map()`.

Here we would need an `expect_map_type` like we have for lists and tuples, possibly first `glb`-ing `ResTy` and `map()` to make the logic easier.

**Comment by gomoripeti** [comment]
Fixed in commit https://github.com/josefs/Gradualizer/commit/6ee4396ececc681eef20d6ce8c04eb4e02ff2e54
