### ISSUE TITLE
Type definitions in records

### ISSUE THREAD

**Issue by Zalastax** [josefs/Gradualizer#185]
When defining records, it's common to annotate each field with its type:
```Erlang
-record(r, {f :: integer(), g :: boolean()}).
```
This is great since it lets Gradualizer and dialyzer report type errors when the record is constructed incorrectly. Unfortunately, records are often used polymorphically, e.g. for match specs:
```Erlang
#r{ f = 1, g = '_'}.
```
Dialyzer will report an error for such usages. The common workaround I've seen is either to ignore those errors or to pollute the type like so:
```Erlang
-record(r, {f :: integer(), g :: boolean() | '_'}).
```
This has led me to believe that writing types directly in the record definition is a misfeature. The alternative I'm proposing is to always write the types separately:
```Erlang
-record(r, {f, g}).

-type r() :: #r{ f :: integer(), g :: boolean()}.
-type r_specable() :: #r{ f :: integer() | '_', g :: boolean() | '_'}.
```
The disadvantage with doing so is that dialyzer can't report an error when you create the record. Instead, the error can only be found if e.g. an `r_specable()` is used where an `r()` is needed.
For us, we have our type annotation functions which could tell gradualizer whether the construction is for `r()` or `r_specable()`. Would it be an advantage to have specific syntax for it as well? We could ship a nice little macro and provide documentation about this idea.

I'm waiting for a response in https://bugs.erlang.org/browse/ERL-892 but wanted to raise the question here as well.

**Comment by zuiderkwast** [comment]
Isn't this is the ordinary record type refinement? This is from Types and Function Specifications:

> Any record, containing type information or not, once defined, can be used as a type using the following syntax:
>
>     #rec{}
>
> In addition, the record fields can be further specified when using a record type by adding type information about the field as follows:
>
>     #rec{some_field :: Type}
>
> Any unspecified fields are assumed to have the type in the original record declaration.

I think it's a good idea to use a refined types as you do, @Zalastax, one for the match specification and another for the actual values.

Do we handle refined record types already?

**Comment by Zalastax** [comment]
@zuiderkwast you're right!

```Erlang
%% OK by dialyzer
-record(r, {f :: integer()  | '_', g :: boolean() | '_'}).
-type r_non_specable() :: #r{ f :: integer(), g :: boolean()}.

%% Not OK by dialyzer
-record(r, {f :: integer(), g :: boolean()}).
-type r_specable() :: #r{ f :: integer() | '_', g :: boolean() | '_'}.
```

Perhaps the recommendation should then be to write the smallest type that can accommodate all your needs in the record definition and then create refinements as needed. For maintainability, even when the the type `#r{}` is exact it should not be used directly. Instead an alias `r() :: r{}` should be created.

**Comment by josefs** [comment]
@Zalastax, can this issue be closed? It's not clear to me that there's anything to be done here.

**Comment by Zalastax** [comment]
Yes, there's nothing we can do at the moment. The issue in the Erlang bug tracker is enough.
