### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by tim2CF** [josefs/Gradualizer#19]
If module passed to `&:gradualizer.type_check_module/1` function contains function calls to other modules, Gradualizer throws error `Call to undefined function ...`. What is the proper way to avoid it?

**Comment by zuiderkwast** [comment]
Gradualizer doesn't find your other modules. Other modules are handled by the module `gradualizer_db`, specifically the function `get_src_map/0`. It is looking for `.erl` files within the the code path to find the source code of each beam file.

I think for Elexir (and possibly for Erlang as well depending on compile options), the beam files are compiled with debug information, which means the parse tree ("abstract code") can be extracted from the beam file instead, using [beam_lib](http://erlang.org/doc/man/beam_lib.html). We should add this to gradualizer_db, either as a fallback or as the first option. Actually, I think extracting it from the beam file should be the first option. Finding the source code is somewhat of a hack.

**Comment by tim2CF** [comment]
thanks!

**Comment by tim2CF** [comment]
created PR
https://github.com/josefs/Gradualizer/pull/20
