### ISSUE TITLE
Dash or underscore for options?

### ISSUE THREAD

**Issue by josefs** [josefs/Gradualizer#213]
We have three ways of specifying options for gradualizer: on the command line, as term in a list when calling through the `gradualizer` api, and using the newly implemented `-gradualizer()` directive (#212, thanks @zuiderkwast). 

It is good that we have all these variants. But. They don't agree on the spelling of the options! For example, we have "--fmt-location" on the command line but `fmt_location` in the `gradualizer` api and in directives. A similar problem for "no-infer" and `no_infer`, "no-prelude" and `no-prelude` and so on.

I don't like this discrepancy and I'd like to get rid of it. I propose that we keep the atoms as they are and change the command line arguments to use underscore.

The root of the problem is that dash ("-") is not part of the atom syntax so if we were to use that, it'd be ergonomically unfriendly. We'd have to quote the atoms and that feels unnecessary. On the other hand, using underscores on the command line is somewhat non-idiomatic so it will look a little weird. But I prefer that in this case. I'd like to optimize for the use of the api and the directives.

**Comment by zuiderkwast** [comment]
Dash as word-separator is common practice for shell commands. Options starting with a dash for single-letter optinos and double-dash for longer ones is common practice. Within Erlang, atoms with underscore is naturally used. I think we are following all the conventions. I wouldn't like `gradualizer --options '[{infer, false}, {fmt_location, brief}]' *.erl` for the shell. I like it the way it is.

**Comment by zuiderkwast** [comment]
Btw, `--no-prelude` should correspond to `{prelude, false}`. I'm not sure it does, but that would be the convention I would expect.

**Comment by zuiderkwast** [comment]
Sorry for spamming. I was thinking we could have a look at other tools such as dialyzer and compiler, how they do it. For dialyzer, they use a hybrid style like `--check_plt` vs `{check_plt, boolean()}`.

**Comment by josefs** [comment]
Thanks for bringing up dialyzer as an example, @zuiderkwast. What I meant to say is that I'd gradualizer to have command line arguments in the same style as dialyzer, i.e. using underscore instead of dash. I **don't** propose that we write erlang terms on the command line. 

As for how the options are treated in the gradualizer api and in directives, I don't have a strong opinion on whether we use `{infer, boolean()}` the presence of absence of the `infer` atom in a list.

**Comment by zuiderkwast** [comment]
Sounds good @josefs. This way, the CLI<->proplist mapping is simpler.

How should we represent the `false` valued AKA `--no-` options then?

Some options are borrowed from compiler/erlc though, with their conventions, e.g. `-I` (`{i, Dir}`), `-pa` (no proplist equivalent).

**Comment by josefs** [comment]
> How should we represent the false valued AKA --no- options then?

In #215 I've done a bit of reorganization of how to treat the `--no-` options based on some convenient functions in `proplists`. Specifically, I've used `normalize` to specify that the `--no-` options are just negations of their non-negated counterparts, which means that there will be no `--no-` options in the options after normalization. That seems to be the most idiomatic way of doing it.

**Comment by josefs** [comment]
This issue is closed by #216 .
