### ISSUE TITLE
Treat term() as the dynamic type

### ISSUE THREAD

**Issue by Zalastax** [josefs/Gradualizer#217]
The discussion in https://github.com/josefs/Gradualizer/pull/205 cumulated in a decision to treat `term()` as the dynamic type, i.e. as `any()`.

@josefs writes
> Cool! It seems that we've reached an agreement on treating `term()` as the dynamic type as well.
> 
> We still need an internal representation for the top of the subtyping hierarchy, for example in `glb`. But that's an implementation detail for whoever implements this change.

**Comment by josefs** [comment]
Just to make sure it's super clear to everyone:

**This means no more overriding the type specs in OTP!**

This will be a major simplification for us.

**Comment by zuiderkwast** [comment]
Can we make it "almost no more"? It can be a useful feature for fixing incorrect or inexact specs in 3rd party code and I think it's still useful to keep a few overrides for OTP, for example `hd([A, ...]) -> A` instead of `hd([term(), ...]) -> term()`.

Let's start! Do we make the change destructively and immediately?

**Comment by FrankBro** [comment]
Does that mean that it would be impossible to constraint `term()` to something more specific in the same way it's not doable for `any()`? If so I don't think it's a good idea. We have some generic storing libraries that are spec'd to explicitly return `term() | undefined` for example. Being able to constraint them is important.

**Comment by josefs** [comment]
@FrankBro, can you elaborate on what you mean? The type `term() | undefined` is equivalent to `term()` so the extra `undefined` is just for documentation purposes.

**Comment by FrankBro** [comment]
I would disagree `term() | undefined` is equivalent to `term()`. The former explicitly states intent: the function will either return something or nothing. `term()` in this situation is just used as a generic parameter. It is indeed for documentation.

**Comment by Zalastax** [comment]
@josefs is technically correct. `term() | undefined` simplifies to `term()`. There might still be value in writing it out for documentation but there's no difference to the type checker.

With this change + the ideas @zuiderkwast has about unions with `any()`, a consumer of `term() | undefined` will have to handle `undefined`. I think that's what you asked for in your first comment.
