### ISSUE TITLE
map-based types support

### ISSUE THREAD

**Issue by timCF** [josefs/Gradualizer#22]
The following code 

```erlang
-type t() :: #{year := integer() | nil,
	       price := integer() | nil,
	       model := 'Elixir.String':t() | nil}.

-spec 'can_buy?'('Elixir.Car':t(),
		 integer()) -> boolean().

'can_buy?'(#{price := Vprice@1}, Vmoney@1)
    when Vprice@1 =< Vmoney@1 ->
    true;
'can_buy?'(#{}, _) -> false.
```

currently not passing Gradualizer checks:

```
The pattern #{price := Vprice@1} on line 10 doesn't have the type 'Elixir.Car':t()
```

Is it bug or feature? I'm asking because big amount of Elixir code uses map-based types.

**Comment by gomoripeti** [comment]
this is a missing feature: map pattern matching is not yet implemented in `add_type_pat/4`

**Comment by timCF** [comment]
thanks! 👍

**Comment by tim2CF** [comment]
Do we have some kind of roadmap?
I can start to learn Erlang AST to implement this feature, but I don't know - maybe somebody else is gonna to implement it, probably faster and better than I can do it :)

**Comment by josefs** [comment]
We don't have any roadmap, though perhaps we should have. My personal roadmap is to try to find the time to properly implement type variables and constraint solving. But I tend to fix smaller missing things as I encounter them. @tim2CF , feel free to hack away on support for maps.

**Comment by zuiderkwast** [comment]
@tim2CF Cheat sheet for Erlang AST: https://github.com/zuiderkwast/erlang_abstract_format

**Comment by zuiderkwast** [comment]
Map patterns are handled now, which the example above is about, so I'm closing this issue. Other things related to maps are still not implemented, e.g. #131
