### ISSUE TITLE
no match of right hand side value: :not_found in prettyprint_and_highlight

### ISSUE THREAD

**Issue by myfreeweb** [josefs/Gradualizer#240]
```
** (MatchError) no match of right hand side value: :not_found
    (gradualizer) /usr/home/greg/src/github.com/myfreeweb/sweetroll2/deps/gradualizer/src/gradualizer_highlight.erl:35: :gradualizer_highlight.prettyprint_and_highlight/3
    (gradualizer) /usr/home/greg/src/github.com/myfreeweb/sweetroll2/deps/gradualizer/src/gradualizer_fmt.erl:399: :gradualizer_fmt.highlight_in_context/2
    (gradualizer) /usr/home/greg/src/github.com/myfreeweb/sweetroll2/deps/gradualizer/src/gradualizer_fmt.erl:364: :gradualizer_fmt.format_expr_type_error/4
    (gradualizer) /usr/home/greg/src/github.com/myfreeweb/sweetroll2/deps/gradualizer/src/typechecker.erl:4119: :typechecker.handle_type_error/2
    (gradualizer) /usr/home/greg/src/github.com/myfreeweb/sweetroll2/deps/gradualizer/src/typechecker.erl:4105: :typechecker."-print_errors/2-lc$^0/1-0-"/2
    (gradualizer) /usr/home/greg/src/github.com/myfreeweb/sweetroll2/deps/gradualizer/src/typechecker.erl:4105: :typechecker.print_errors/2
    (gradualizer) /usr/home/greg/src/github.com/myfreeweb/sweetroll2/deps/gradualizer/src/gradualizer.erl:196: :gradualizer.type_check_forms/3
    lib/gradualixir.ex:71: Gradualixir.safe_type_check_file/2
```

[beam file](https://dl.unrelenting.technology/gradualizer_err_serve.beam), [source](https://github.com/myfreeweb/sweetroll2/blob/7313e61d6fe845abbfed37c966dc030564e20255/lib/sweetroll2/serve.ex) (almost — it's been changed a tiny bit)

**Comment by josefs** [comment]
Hi @myfreeweb. How did you invoke gradualizer? 

I'm afraid we don't officially support elixir, we currently don't have an elixir person to make sure graudalizer works as expected for that language. 

That being said, this problem looks easy to fix. The syntax high lighter needs another case to deal with the elixir atom. Feel free to submit a pull request!

**Comment by lukaszsamson** [comment]
I stumbled on this crash when using https://github.com/OvermindDL1/gradualixir wrapper

**Comment by zuiderkwast** [comment]
I tried reproducing it by checking the supplied beam file using `gradualizer gradualizer_err_serve.beam` but it gave me some other error.

I have however also noticed that Gradualixir has a printout saying "Report this error to Gradualizer:" here: https://github.com/OvermindDL1/gradualixir/blob/master/lib/gradualixir.ex#L84

**Comment by josefs** [comment]
> I have however also noticed that Gradualixir has a printout saying "Report this error to Gradualizer:" here: https://github.com/OvermindDL1/gradualixir/blob/master/lib/gradualixir.ex#L84

Uhm, ok. For most errors that's fair, but It'd be good if it didn't say that for the `:not_found` error.

**Comment by zuiderkwast** [comment]
It's calling Gradualizer in a try-catch, so the errors caught here are exceptions bubbling out from Gradualizer. `:not_found` is just Elixir syntax or the Erlang atom `not_found`, which is handled by doing another attempt to find the stuff to highlight withing the whole AST, but this time without first truncating the AST. If it returns `not_found` the second time, this exception happens. I don't understand how the node to highlight is not found...

**Comment by josefs** [comment]
Ok. As I said above, the fix is easy but it's not high on my priority list and I don't have a way of reproducing it currently.

**Comment by zuiderkwast** [comment]
The error was in traversing the AST. I had assumed that every node has an annotation as the second element, but there is one which hasn't: `{clauses, [...]}` which is wrapping the body of a 'fun'.
