### ISSUE TITLE
Record refinement via function clauses

### ISSUE THREAD

**Issue by FrankBro** [josefs/Gradualizer#245]
Here is what I'm trying to get working:

```erlang
-module(test).

-export([args/1, tuple/1, record/1]).

-spec args(integer() | undefined, integer()) -> integer().
args(undefined, I) -> I;
args(I, _) -> I.

-spec tuple({integer() | undefined, integer()}) -> integer().
tuple({undefined, I}) -> I;
tuple({I, _}) -> I.

-record(test, {
    field :: integer() | undefined
}).

-spec record(#test{}, integer()) -> integer().
record(#test{field = undefined}, I) -> I;
record(#test{field = I}, _) -> I.
```

The last test does not pass because we don't do refinement for records it seems. In fact, in `add_type_pat`, the type returned is always `type(none)`. 

I'm trying to implement this but not sure how to do it. Looking at the tuple, one thing that is nice is that we'll always have every fields and the type for a record is pretty easy to figure out:
`{type, _, tuple, [Field1, Field2]}`. The only type I've ever constructed for records had its name and that's it: `{type, _, record, [{atom, _, Name}]}`. How can I inject some fields being eliminated? 

Here is another examples with steps:

```erlang
-spec test({undefined | integer(), undefined | integer()}) -> integer().
test({undefined, undefined}) -> 0;
test({undefined, B}) -> B;
test({A, undefined}) -> A;
test({A, B}) -> A + B.
```

The type will be stepped this way:

```erlang
{type,0,tuple, [{type,0,union, [{atom,0,undefined}, {type,0,integer,[]}]}, {type,0,union, [{atom,0,undefined}, {type,0,integer,[]}]}]}
{type,0,union, [{type,0,tuple, [{type,0,integer,[]}, {type,0,union, [{atom,0,undefined},{type,0,integer,[]}]}]}, {type,0,tuple, [{type,0,union, [{atom,0,undefined},{type,0,integer,[]}]}, {type,0,integer,[]}]}]}
{type,0,union, [{type,0,tuple, [{type,0,integer,[]},{type,0,integer,[]}]}, {type,0,tuple, [{type,0,integer,[]}, {type,0,union, [{atom,0,undefined}, {type,0,integer,[]}]}]}]}
{type,0,tuple, [{type,0,integer,[]},{type,0,integer,[]}]}
```

- First line is the full type. 
- Second line created a union for the two possibilities where `undefined` is defined on either the left or right side.
- Third line eliminated the possibility that the left side would have `undefined`
- Forth line has seen every instances of `undefined` removed.

Technically, a record is a tuple so I assume this should be supported. How can I encode something similar? It would start as

```erlang
{type,0,tuple, [{type,0,record,[{atom,0,test}], {type,0,integer,[]}]}
???
```

**Comment by zuiderkwast** [comment]
Good plan!

You can use `typelib:parse_type/1` to find out how a type is represented:

```
$ make shell
erl -pa ebin
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> typelib:parse_type("#rec{field1 :: integer()}").
{type,1,record,
      [{atom,1,rec},
       {type,1,field_type,[{atom,1,field1},{type,1,integer,[]}]}]}
```

**Comment by josefs** [comment]
As @zuiderkwast said, good plan!

> How can I inject some fields being eliminated?

Can you elaborate on what you mean by this question? I don't understand what it is that you don't understand.

**Comment by FrankBro** [comment]
I think @zuiderkwast might have answered my question but basically, as with the previous example, I would expect the types to go like this for this example:

```erlang
-record(test, {
    field :: integer() | undefined
}).

-spec record(#test{}, integer()) -> integer().
record(#test{field = undefined}, I) -> I;
record(#test{field = I}, _) -> I.
```

```erlang
% Fist call
{type,0,tuple, [
    {type,0,record,[
        {atom,0,test}
    ], 
    {type,0,integer,[]}
]}
% After first clause passed, field cannot be undefined anymore
{type,0,tuple, [
    {type,0,record,[
        {atom,0,test},
        {type,0,field_type,[{atom,0,field},{type,0,integer,[]}]} % here, field, isnt a union of undefined and integer anymore
    ],
    {type,0,integer,[]}
]}
```

Not sure if that notation is ok. Currently trying to implement this.

**Comment by josefs** [comment]
Ah, good. In case you're wondering, the type of the fields in a record lives in the environment that is passed around (typically called `TEnv`).

**Comment by FrankBro** [comment]
Yep, already got that part. Hoping I might have a PR ready for initial comments before next week :)

**Comment by FrankBro** [comment]
Do you guys think it's a good idea to always expand records? I'm still working on the record refinement branch but the edge cases are real hard to deal with. Basically, since records are handled as tuples, I feel like it might be easier to handle them that way. I was trying to be clever and only keep refined fields but it's super hard to deal with. A few examples:

```erlang
-record(r, {f1 :: integer() | undefined, f2 :: integer() | undefined}).

-spec test1(#r{}) -> #r{}.
test1(R) -> R.
```

R's type is `{type, _, record, [{atom, _, r}]}`.

```erlang
-spec test2(#r{}) -> integer().
test2(#r{f1 = undefined}) -> 0;
test2(#r{f1 = I}) -> I.
```

I could see the refinement step being:

```erlang
{type, _, record, [{atom, _, r}]} % before first clause
{type, _, record, [{atom, _, r}, {type, _, integer, _}} % after first step, undefined is out
{type, _, none, _} % we are done, we've matched everything
```

Now let's do f2 first:

```erlang
-spec test3(#r{}) -> integer().
test3(#r{f2 = undefined}) -> 0;
test3(#r{f2 = I}) -> I.
```

What's the refinement step here?

```erlang
{type, _, record, [{atom, _, r}]} % before first clause
{type, _, record, [{atom, _, r}, {type, _, union, [{atom, _, undefined}, {type, _, integer, _}]}, {type, _, integer, _}]} % after first step, undefined is out
{type, _, none, _} % we are done, we've matched everything
````

Right now we mostly (or always?) keep records only as typed as their name are. 

```erlang
{type, _, record, [{atom, _, record_name}]}
```

Should we always expand records fully. Included all their arguments. Man typechecking records is annoying.

**Comment by zuiderkwast** [comment]
Yes, I think we can expand then when we normalize them, so that when we normalize `#r{}` we get `#r{f1 :: integer() | undefined, f2 :: integer() | undefined}`.

It would however be nicer to see just `#r{}` in the error messages. Perhaps we can reverse it when we pretty-print a type? I mean if all the fields have a type identical to the definition of the record, it can be turned back to `#r{}` when we print it.

**Comment by FrankBro** [comment]
I was thinking the same thing. If the fields haven't been refined, print just `#r{}`. If only one field was refined, maybe just print that as well? Like `expected #r{f1 :: integer()} but got #r{f1 :: integer() | undefined`.
