### ISSUE TITLE
Smart matching doesn't influence type of variables

### ISSUE THREAD

**Issue by FrankBro** [josefs/Gradualizer#270]
This should work, erlang makes sure both are the same integer value in this situation. 

```erlang
-module(test).

-spec test(integer() | undefined, integer()) -> integer().
test(I, I) -> I;
test(undefined, I) -> I;
test(I, _) -> I.
```

```
The variable on line 4 at column 9 is expected to have type integer() but it has type integer() | undefined

-spec test(integer() | undefined, integer()) -> integer().
test(I, I) -> I;
        ^
```

**Comment by josefs** [comment]
That's a nice example, I hadn't thought about this problem before. It's tricky to deal with given how the typechecker currently works, but I agree that we could handle this better. Please submit a PR that adds this example under known problems so we can keep track of it.

I'm curious, is this a problem you've come across in practice?

**Comment by FrankBro** [comment]
Nah I just thought about testing it while finishing my record refinement branch (which I hope to create a PR for tomorrow 🤞)
