### ISSUE TITLE
List comprehension vs lists:map: term resolution?

### ISSUE THREAD

**Issue by FrankBro** [josefs/Gradualizer#278]
I'm assuming list comprehension is a specific case and keeps their type while `lists:map`, by using it's definition, has `term()`. This kind of goes back to the concern I had initially with `term()` not being refined anymore. How hard would it be to support this, basically allow usage of `term()` as a generic parameter. Only `process1` complains there.

```erlang
-module(test).

-spec inc(integer()) -> integer().
inc(I) -> I + 1.

-spec process1([{atom(), atom()}]) -> [{atom(), integer()}].
process1(Xs) -> [{A, inc(I)} || {A, I} <- Xs].

-spec process2([{atom(), atom()}]) -> [{atom(), integer()}].
process2(Xs) -> lists:map(fun {A, I} -> {A, inc(I)} end, Xs).
```

This to me exposes a problem. We miss a lot of good opportunity at typing if we don't bother with high-order functions. Possibly adding specific cases for a lot of the BIFs in a few select modules? Like `lists`, `maps`.

**Comment by zuiderkwast** [comment]
We already have a mechanism to override specs of various functions. Our spec for `lists:map/2` ([defined here](https://github.com/josefs/Gradualizer/blob/master/priv/prelude/lists.specs.erl)) is

```Erlang
-spec map(fun((A) -> B), [A]) -> [B].
```

I think the problem is that we don't solve the constraints yet.

**Comment by FrankBro** [comment]
I was unaware of this. Apparently, my problem was elsewhere so I'll just close this. Thanks 😅
