### ISSUE TITLE
Should not pass on malformed expression.

### ISSUE THREAD

**Issue by FrankBro** [josefs/Gradualizer#288]
Simple example, returns no error, even if there is a syntax error.

```erlang
-record(r, {
    integer :: integer()
}).

-spec incr(integer()) -> integer().
incr(I) -> I + 1.

-spec test() -> integer().
test() ->
    Record = #record{integer = 0},
    incr(Record.integer). % Should be Record#r.integer
```

**Comment by FrankBro** [comment]
Is it important if trying to compile it with Erlang itself throws an error?

```
syntax error before: '.'
```

**Comment by Zalastax** [comment]
There's this idea that Gradualizer should in theory be possible to embed in the compiler so it should handle syntax errors and not rely on the compiler to detect syntax errors. I think an error should be produced here. Adding a special case for this abstract format should do the trick!

**Comment by gomoripeti** [comment]
What happens in this case is that the AST contains some error entries
```
...
     {attribute,10,spec,
                {{test,0},
                 [{type,10,'fun',
                        [{type,10,product,[]},{type,10,integer,[]}]}]}},
     {error,{13,erl_parse,["syntax error before: ","'.'"]}},
     {eof,14}]}
```
Maybe gradualizer_file_utils could scan the AST forms to find such error entries and report it.
But there is also value in being able to check incomplete code, ie gradualizer can report type errors in other functions, and you already have a great tool to find syntax errors, the compiler.

**Comment by zuiderkwast** [comment]
I think we should pass the AST to `compile:forms/2` with option `basic_validation`, which is "fast way to test whether a module will compile successfully".

Then we can also remove all the checks that the complier does, such as undefined functions, types, records, etc. (Note though that the compiler doesn't check for remote undefined functions and types.)
