### ISSUE TITLE
erlang:get_stacktrace/0 will be removed in OTP 24

### ISSUE THREAD

**Issue by zuiderkwast** [josefs/Gradualizer#299]
I think we can drop compatibility with OTP < 21 now and switch to `catch C:E:S` everywhere.

**Comment by josefs** [comment]
In general I'm positive to this change. Though I don't have a good sense of if some of our users are still running OTP < 21 still.

**Comment by zuiderkwast** [comment]
IMHO, supporting 2 or 3 old OTP releases should be enough. That's what many projects do, sometimes even less. For example, Cowboy requires OTP 22 now. (When we decided to support OTP 19, the latest OTP was 21.)

**Comment by josefs** [comment]
Yeah, I agree. Furthermore, Gradualizer is not even in beta :-)

**Comment by zuiderkwast** [comment]
Fixed by #301.
