### ISSUE TITLE
Add property based tests using Proper's new Erlang AST generator

### ISSUE THREAD

**Issue by zuiderkwast** [josefs/Gradualizer#313]
Proper has new a module called "proper_erlang_abstract_code" [1] which generates abstract code. It can be used to check that we don't crash on any program or to find things we didn't think about. Apparently, the OTP team is using it [2] for testing OTP compiler and such.

[1] https://github.com/proper-testing/proper/blob/master/src/proper_erlang_abstract_code.erl
[2] https://github.com/proper-testing/proper/pull/255

(I wonder if it generates improper lists :laughing:)

**Comment by erszcz** [comment]
Done a while ago with #363.
