### ISSUE TITLE
Handling aliases correctly

### ISSUE THREAD

**Issue by TheGeorge** [josefs/Gradualizer#32]
Currently the following code
```erlang
-spec test() -> {atom1, atom2} | atom3.
test() ->
    case f() of
        {atom1, _} = X -> X;
        _ -> atom3
    end.

-spec f() -> {atom1, atom2} | atom4.
f() ->
    {atom1, atom2}.
```
gives me the error
```
The variable 'X' on line 7 has type {atom1, atom2} | atom4 but is expected to have type {atom1, atom2} | atom3
```

**Comment by zuiderkwast** [comment]
Shouldn't solving the constraints be enough in this case? It's not implemented, but from the pattern `{atom1, _} = X`, there should be a constraint `X :: {atom1, _}` which can be used to eliminate `atom4`.

**Comment by josefs** [comment]
@zuiderkwast, your suggestion implies that we can infer the type of the pattern. I suppose we could attempt to do that, but it's not something we currently do.

**Comment by josefs** [comment]
I just want to mention that I've come across this problem myself now. I didn't write the code but I've type checked a few modules which use this idiom.
