### ISSUE TITLE
Gradualizer may fall into infinite loop for recursive types.

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [josefs/Gradualizer#322]
A repro:

```erlang
-module(recursive_types).

-compile([export_all, nowarn_export_all]).

-type rec1(A) :: A | {rec, rec1(A)}.

-spec unwrap(rec1(rec1(atom()))) -> rec1(atom()).
unwrap({rec, Z}) -> Z.
```

This goes into loop:
```
./bin/gradualizer recursive_types.erl
```

**Comment by gomoripeti** [comment]
very nice minimal example
This reminds me of https://github.com/josefs/Gradualizer/pull/135, apparently the cache did not solve all cases :(

**Comment by mheiber** [comment]
Not sure if a similar example has been covered already, but I'm seeing an infinite loop with the following code:

```erl
-module(sample).
-compile([export_all]).

-type t() :: t().

-spec main() -> t().
main() -> ok.
```

tested with `208f5816b0157f282212fc036ba7560f0822f9fc` (master)

**Comment by zuiderkwast** [comment]
@mheiber thanks for this example. I think it's a different issue. Types can refer to itself inside a tuple etc. but it's allowed to be recursive on the top level, so we should detect it and give an error for this.

**Comment by mheiber** [comment]
Thanks for confirming, @zuiderkwast . Would it be better for me to open a separate issue, or would you prefer to keep these recursive types issues together?

**Comment by zuiderkwast** [comment]
Separate please (unless you think it will be solved by the same fix??)

**Comment by mheiber** [comment]
> Separate please (unless you think it will be solved by the same fix??)

I think both issues have to do with checking subtype or type equivalence for recursive types–I suspect they will have a common solution.
