### ISSUE TITLE
Local types are resolved as remote types when using generics

### ISSUE THREAD

**Issue by berbiche** [josefs/Gradualizer#326]
I couldn't find any issue detailing this bug but given the following files:

`user_types.erl`
``` erlang
-module(user_types).

-type my_atom() :: atom().
-type my_shadowed_local() :: user_types.
-type my_generic(T) :: my_atom() | {ok, T}.

-export_type([my_generic/1]).
```

and 

`remote_types.erl`
``` erlang
-module(remote_types).

-type my_shadowed_local() :: remote_types.

-spec my_function(atom()) -> user_types:my_generic(my_shadowed_local()).
my_function(undefined) -> error.
my_function(_) -> {ok, remote_types}.
```

This fails to typecheck because `my_shadowed_local` is resolved in the "context" of the `user_types` module.

**My understanding**

```
62:1: Checking clause :: user_types:my_generic(my_shadowed_type())
62:47: Checking that {ok, shadowed} :: user_types:my_generic(my_shadowed_type())
[type_check_expr_in:2063] {remote_type,0,
                              [{atom,{61,53},user_types},
                               {atom,{61,64},my_generic},
                               [{user_type,0,my_shadowed_type,[]}]]}
```

Starting from `type_check_expr_in(Env, ResTy, Expr)`, the `ResTy` does not have any information about the provenance of the `user_type`.

`normalize` is then called before going into `do_type_check_expr_in`.
`[normalize:655] get_exported_type{remote_type, M :: user_types, N :: my_generic, Args :: [{user_type, 0, my_shadowed_type, []}]}`.

We make it to `gradualizer_db` to get the exported type:
`[handle_call:174] (get_exported_type) M :: user_types, T :: my_generic, Args :: [{user_type,0,my_shadowed_type,[]}`,
which handles the call and ends up in `handle_get_type`.

`handle_get_type` finds the exported type `my_generic` and calls `typelib:substitute_type_vars`:

``` erlang
{type,16,union,
             [{user_type,16,my_atom,[]},
              {type,16,tuple,
                    [{atom,16,ok},{user_type,0,my_shadowed_type,[]}]}]}
```

It then calls `typelib:annotate_user_types(ModuleOfTheExportedType, Type)`:

``` erlang
{type,16,union,
             [{user_type,[{file,"user_types.erl"},{location,16}],my_atom,[]},
              {type,16,tuple,
                    [{atom,16,ok},
                     {user_type,[{file,"user_types.erl"},{location,0}],
                                my_shadowed_type,[]}]}]}
```

Where `annotate_user_types` simply adds the filename from the module to all the types:

``` erlang
annotate_user_types(Module, Type) when is_atom(Module) ->
    annotate_user_types(atom_to_list(Module) ++ ".erl", Type);
annotate_user_types(Filename, {user_type, Anno, Name, Params}) ->
    %% Annotate local user-defined type
    {user_type, erl_anno:set_file(Filename, Anno), Name,
     [annotate_user_types(Filename, Param) || Param <- Params]};
...
```

edit: I think this behavior exists to be able to find `my_atom()` type in the example above.

My takeaway is that when `gradualizer_db` is interrogated, it doesn't have enough information about the origin of a `user_type`.

I'm currently experimenting with the following solution:
1. Annotate all types with a filename when parsing forms.
2. Pass TEnv to `gradualizer_db:get_exported_type` to retrieve the types and their annotation.

``` erlang
{tenv,remote_types,
    #{},
      {local_list,0} =>
          {[],
           {type,
               [{file,"remote_types.erl"},{location,0}],
               list,
               [{type,0,atom,[]}]}},
      {local_record_with_remote_type,0} =>
      {my_shadowed_type,0} => {[],{atom,0,shadowed}}}
}
```

**Comment by josefs** [comment]
Excellent bug report! 
I'm not a big fan of your solution 1. We try to stay as close as possible to the abstract format and I'd like to keep it that way.
Solution 2 on the other hand sounds like the right thing to do. Looking forward to a PR!

**Comment by berbiche** [comment]
Hi,

Solution 1 adds filenames to annos which is already supported by mean of `erl_anno:set_file/2`.
Solution 2 would not be enough for the following case:

`user_types.erl`
``` erlang
-export_type([my_shadowed_type/0, my_generic/1]).
%% my_shadowed_type doesn't even have to be exported
-type my_shadowed_type() :: user_types.
-type my_generic(T) :: my_shadowed_type() | {ok, T}.
```

`remote_types.erl`

``` erlang
-type my_shadowed_type() :: remote_types.

-spec F(atom()) -> user_types:my_generic(my_shadowed_type()).
F(a) -> user_types;
F(_) -> {ok, remote_types}.
```

`my_shadowed_type()` is a `user_type` in both cases, but in only one of them it is local to the `remote_types` module.

This is why both solutions would be required to fix the problem.

**Comment by josefs** [comment]
Ah, I see. I mistunderstood your point 1. Sounds good!

**Comment by zuiderkwast** [comment]
> I think this behavior exists to be able to find my_atom() type in the example above

That's right. I added this code. It's a bit ugly to make up a filename by just adding .erl to the module name, but it worked.

Any of the solutions 1 and 2 are fine with me. Go for the one you think is best. :) Solution 2 would have to include unexported types in the TEnv, right?

**Comment by berbiche** [comment]
If I'm not mistaken, the TEnv only includes types from the currently checked module so it should also include unexported types.

**Comment by zuiderkwast** [comment]
> If I'm not mistaken, the TEnv only includes types from the currently checked module so it should also include unexported types.

Right. I've not looked at the this for a while. I don't know what would be needed to make solution 2 work. Perhaps solution 1 is better then: annotate type to prevent it from being interpreted in the context of the remote module.
