### ISSUE TITLE
How to help Gradualizer 

### ISSUE THREAD

**Issue by Zabrane** [josefs/Gradualizer#329]
Hi @josefs  

I'm struggling on how i to help `Gradualizer` to not emit an error.

As you can see, function `always_find/2` never fails in my case because I've a guarantee that `Key` always exists.
Hence the `{_, _} = ...`.

But `Gradualizer` thinks it might return `false` (which can't happen). How can i prevent that?

```erlang
-type leaf()  :: {integer(), string()}.

-spec always_find(integer()) -> leaf().
always_find(Key) ->
  {_, _} = lists:keyfind(Key, 2, L).


btree.erl: The function call on line 95 at column 19 is expected to have type leaf() but it has type tuple() | false

-spec always_find(integer(), [leaf()]) -> leaf().
always_find(Key, L) ->
  {_, _} = lists:keyfind(Key, 2, L).
           ^^^^^^^^^^^^^^^^^^^^^^^^                    
```

**Comment by josefs** [comment]
Hi @Zabrane 

If you want to have a function which throws an exception when it doesn't find the key, it's better to use `case` explicitly. I would suggest something like this:

``` . erlang
-spec always_find(integer()) -> leaf().
always_find(Key) ->
  case lists:keyfind(Key, 2, L) of
    res@{_, _} -> res;
    false -> throw({undefined_key, Key})
  end.

```

**Comment by Zabrane** [comment]
@josefs searched Key are always present and the call never fails as explained before. Returning an `exception` isn't the best way to solve this Gradualizer's `false-positive`. Moreover, it makes the code slower due to the `case ... of`.

**Comment by josefs** [comment]
If you are 100% sure the call will never return `false` you can use the `?assert_type` macro, like so:

```
-spec always_find(integer()) -> leaf().
always_find(Key) ->
  ?assert_type( lists:keyfind(Key, 2, L) , leaf() ).
```

The macro is in `gradualizer.hrl`.

**Comment by Zabrane** [comment]
@josefs ahhh thanks. Exactly what i was looking for
