### ISSUE TITLE
[Knowledge sharing] unions of any()

### ISSUE THREAD

**Issue by Zalastax** [josefs/Gradualizer#33]
Coming from TypeScript I was curious why they choose to absorb T in `T | any` which becomes `any`.
The answer is simple: [performance](https://github.com/Microsoft/TypeScript/issues/18568). Is there any literature on the implications of doing it as they do vs doing it as we do?

Is there a communication channel for just general discussion? I just wanted to have this in print and easily accessible - close when my meta question(s) are resolved!

**Comment by zuiderkwast** [comment]
Yes, I implemented normalization of unions. We merge any non-any types but keep any separate. @josefs, you showed an example of this yourself during the demo in last Design Forum. The error message was something like *integer() | any() is not a compatible subtype of non_neg_integer()*.

The reasoning was that a value of type `integer() | any()` can at least be any positive or negative integer. Apart from this, it can possibly also be a value of other types that we don't know.

We merge anything else, so for example `integer() | 42 | any()` = `integer() | any()`.

**Comment by gomoripeti** [comment]
just expanding on this, I think the optimisation only work one way.

(`::` is compatible subtype).
- `t2() :: t1() | any()` is equivalent with `t2() :: any()` (in this case union means `t2() :: t1()` *OR* `t2() :: any()`)
- but `t1() | any() :: t2()` is not equivalent with `any() :: t2()` (in this case union translates to `t1() :: t2()` *AND* `any() :: t2()`).

**Comment by Zalastax** [comment]
@gomoripeti I *think* that is what they say in "Fig. 8. Merge operator" of "The Recursive Union of Some Gradual Types" - don't hold me accountable though.
