### ISSUE TITLE
Publish it on hex.pm

### ISSUE THREAD

**Issue by gilbertwong96** [josefs/Gradualizer#331]
When I want to depend it in my projects, I found that I have to depends it from GitHub. 

It is a good way to publish the release to [hex.pm](https://hex.pm), which means that I can use semver-like syntax to declare the dependency like `{rebar, "~> 2.0.0"}` to get patch version update automatically.

**Comment by zuiderkwast** [comment]
It requires some extra maintenance to publish on Hex every time, so we need someone who would be willing to do that. Any volunteers?

Besides, the project is beta/experimental and we barely even tag any versions in git...

**Comment by gilbertwong96** [comment]
I'm willing to be the contributor of this project! @zuiderkwast

**Comment by zuiderkwast** [comment]
Fine be me.

@FrankBro you have added the git tags. Any plan to tags versions regularily?

@josefs WDYT?

**Comment by josefs** [comment]
Thanks for stepping up @gilbertwong96 ! Much appreciated!
I don't know much about hex. Who will have control over uploading new version to it? I think it'd be good if you weren't the only one who could do that, @gilbertwong96.

**Comment by zuiderkwast** [comment]
I have a hex account: zuiderkwast. You can add me as a backup.

**Comment by berbiche** [comment]
@zuiderkwast I can't talk on behalf of Frankbro, but most of his work on Gradualizer/Erlang was part of his work at AdGear.

I suppose it would be possible to automate releases.
With proper permissions, only tags on master/main branch would trigger a release workflow that would both publish to hex.pm and make a release on GitHub.
Pushing directly to master/main would be restricted in the repo's branch security configuration.

Automating releases would reduce the burden of publishing to hex.

**Comment by zuiderkwast** [comment]
@berbiche again, fine with me, if you (or someone else) sets it up and takes care of any future issues that might come up with it. :-)

**Comment by gilbertwong96** [comment]
> I have a hex account: zuiderkwast. You can add me as a backup.

Ok. I plan to try GitHub action to do automating releases.

**Comment by gilbertwong96** [comment]
PR here: https://github.com/josefs/Gradualizer/pull/332
@josefs

**Comment by zuiderkwast** [comment]
Current and old versions are published already: https://hex.pm/packages/gradualizer
