### ISSUE TITLE
UX: Gradualizer should indicate when a record, etc. is missing from the environment

### ISSUE THREAD

**Issue by berbiche** [josefs/Gradualizer#336]
As part of tech debt work on a large codebase, one file used an `include` with a path that worked when invoked by rebar3 during compilation, but not rebar3 gradualizer (this isn't the point of this issue).

This file defines records and types, and since they were missing from the environment, pattern checking against these records would give useless errors.

https://github.com/josefs/Gradualizer/blob/208f5816b0157f282212fc036ba7560f0822f9fc/src/gradualizer_fmt.erl#L318-L325
https://github.com/josefs/Gradualizer/blob/e226803c023bf9ceb94dfb517068208af37b9d7f/src/typechecker.erl#L3865-L3866
https://github.com/josefs/Gradualizer/blob/e226803c023bf9ceb94dfb517068208af37b9d7f/src/typechecker.erl#L1122-L1124
https://github.com/josefs/Gradualizer/blob/e226803c023bf9ceb94dfb517068208af37b9d7f/src/typechecker.erl#L1135-L1137

I propose the `expect_record_type` function head above return a different error for a missing type in the environment.

The error message in gradualizer_fmt could be something like ```"<location>: The record <record> type is not defined. Are you using the right `-include`?"```

Let me know what you think. This is a quick fix/win!

**Comment by zuiderkwast** [comment]
It wound't compile in this case. It means it can't happen when checking abstract code from beam files, but only when checking erl files (or AST from elsewhere).

I think the proper solution is this: https://github.com/josefs/Gradualizer/issues/288#issuecomment-641258820. I never created an issue nor a PR, but I think it's the way to go.
