### ISSUE TITLE
Exhaustiveness check for tuple expressions in case_of fails

### ISSUE THREAD

**Issue by berbiche** [josefs/Gradualizer#339]
Hi,

I did not find a similar issue opened.

I encountered an issue where the refined type for a `case of` is `any()` while the type used
to check for `refinable` is a `tuple` if too many fields are checked against.

I have not done a deep dive of the issue yet but the sample code below will reproduce the issue.

``` erlang
-type union_a() :: a | b | c | d | e.
-type union_b() :: m | n.

-spec union_atom(undefined | union_a(), undefined | union_b()) -> {}.
union_atom(X, Y) ->
    %% The second field does not seem to matter
    case {X, Y} of
        {a, m} -> {};
        {b, m} -> {};
        {c, m} -> {};
        {d, m} -> {};
        %% Commenting out the next match will NOT produce the error
        {e, m} -> {};
        %% Swapping the match above with any of the next matches also reproduce the error
        %% This seems to indicate that the number of matches is the problem
        %{a, n} -> {};
        %{b, n} -> {};
        %{_, undefined} -> {};
        %{undefined, _} -> {};
        {_, _} -> {}
    end.

%% The minimum amount of fields in the union
%% to reproduce the issue seems to be (3x5) or (5x3)
-spec union_atom_inline(union_a(), union_b() | o) -> {}.
union_atom_inline(X, Y) ->
    case {X, Y} of
        {a, m} -> {};
        {b, m} -> {};
        {c, m} -> {};
        {d, m} -> {};
        %% Commenting out the next match will NOT produce the error
        {e, m} -> {};
        {_, _} -> {}
    end.
```

Replacing the above `case of` with function patterns will not result in an error.
Changing the last match for `_` also fixes the issue.

Stacktrace:
```
escript: exception error: no function clause matching
                 gradualizer_lib:pick_value({type,0,any,[]},
                                            #{module => exhaustive,
                                              records => #{},
                                              types =>
                                               #{{union_a,0} =>
                                                  {[],
                                                   {type,0,union,
                                                    [{atom,0,a},
                                                     {atom,0,b},
                                                     {atom,0,c},
                                                     {atom,0,d},
                                                     {atom,0,e}]}},
                                                 {union_b,0} =>
                                                  {[],
                                                   {type,0,union,
                                                    [{atom,0,m},
                                                     {atom,0,n}]}}}}) (src/gradualizer_lib.erl, line 137)
  in function  gradualizer_lib:'-pick_value/2-lc$^0/1-2-'/2 (src/gradualizer_lib.erl, line 138)
  in call from typechecker:check_exhaustiveness/6 (src/typechecker.erl, line 3201)
  in call from typechecker:do_type_check_expr_in/3 (src/typechecker.erl, line 2239)
  in call from typechecker:type_check_expr_in/3 (src/typechecker.erl, line 2034)
  in call from typechecker:check_clause/5 (src/typechecker.erl, line 3226)
  in call from typechecker:'-check_clauses/5-fun-0-'/6 (src/typechecker.erl, line 3183)
  in call from lists:foldl/3 (lists.erl, line 1267)
```

**Comment by berbiche** [comment]
Off-topic but why is the non-refined type used in `refinable()` checks while the refined one is used in `pick_value`?

**Comment by zuiderkwast** [comment]
> why is the non-refined type used in `refinable()` checks

I don't know. I think the refined type (the actual type, with all parameters) should be used in `refinable()`. Can we change it and see if anything breaks?

**Comment by erszcz** [comment]
I think `any()` will never be `refinable()` (unless, maybe, until we use negative types, but I'm not sure now if that would be useful for any purpose).

Judging from a quick glance, I think the original issue could've happened because of https://github.com/josefs/Gradualizer/blob/6e89b4e1cd489637a848cc5ca55058c8a241bf7d/src/typechecker.erl#L765-L766 Does it occur even if we do `gradualizer --union_size_limit X ...` with X=50 or even X=100? It's possible to pass this as a flag for some time, so testing the original example should be easier.

**Comment by zuiderkwast** [comment]
(I think negative types can be useful for refinement of any(). Example:

```Erlang
-spec f(any()) -> any().
f({X, Y}) -> {Y, X};
f({_, _}) -> ok. % <--- Can't match. The parameter is `any() \ {_, _}` here.
```

I don't think we should add it though, since it adds complexity and I think it might be inefficient with the current type representation.)

**Comment by berbiche** [comment]
> Judging from a quick glance, I think the original issue could've happened because of
> 
> https://github.com/josefs/Gradualizer/blob/6e89b4e1cd489637a848cc5ca55058c8a241bf7d/src/typechecker.erl#L765-L766
> Does it occur even if we do `gradualizer --union_size_limit X ...` with X=50 or even X=100? It's possible to pass this as a flag for some time, so testing the original example should be easier.

Thanks, I forgot about this particular flag/behavior.
The issue is resolved once this flag is changed.

**Comment by erszcz** [comment]
> I forgot about this particular flag/behavior.

The CLI option didn't exist back in Aug 2021 when this ticket was created. The option only got introduced in https://github.com/josefs/Gradualizer/pull/341.

Good that we found the culprit! Thanks @berbiche for checking again :+1:
