### ISSUE TITLE
Flag to enable type checking per file in a project

### ISSUE THREAD

**Issue by Zalastax** [josefs/Gradualizer#34]
In the JavaScript world, [Flow](https://flow.org/en/docs/usage/#toc-prepare-your-code-for-flow) and [TypeScript](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html) can enable type checking on a per file basis in a project setup. This allows for gradual enabling of the type checker so that there is not an overwhelming amount of errors when starting out. Without a similar solution I think it will be difficult to add gradualizer to a big code base - especially if we do a good job with type inference.

**Comment by zuiderkwast** [comment]
I think it is a good suggestion. I would like a type checker to be able to detect as many `badarg` errors in runtime as possible.

This can already be done in the build scripts and tools for each project. For small projects, I think it can be enabled in one go. It could be enabled using configuration in the rebar config file or Makefile. For larger projects, a build tool can make use a list of files to type check. A continuous integration tool can keep track of the number of errors and to highlight new errors introduced by a commit or a build.

I don't think it would be very sexy to have type checking annotation in each file, such as `-compile(check_types)` if that's what you're suggesting. This should be the default IMO.

In the long run, I think is a reasonable that a typechecker (this or another) becomes part of the Erlang compiler. Compiler options such as `nowarn_type_error` could be added. Erlang has a syntax for types that the compiler doesn't check, apart from the syntax of the types. It seems like the language designers have somehow prepared for a type checker which doesn't exist yet. (Dialyzer doesn't really use the type specs. The annotations are basically just used for documentation, by tools like EDoc.)

**Comment by gomoripeti** [comment]
I agree this is a good, practical idea. Gradualizer itself already works on a per module basis (`gradualizer:type_check_file`) so this could be the responsibility of the build tool plugins. The cli you created already takes a list of files as arg so it already supports this "large project one-by-one" approach.

**Comment by Zalastax** [comment]
@gomoripeti I think you're absolutely right! If I understand the source correctly, gradualizer mostly (only?) reports errors for the modules you list and there isn't really a need to add the concept of a project since gradualizer keeps a database of types running in between the separate calls to `gradualizer:type_check_file`.

Is there anything actionable here or should we just keep this in mind for the future? I feel there might be some nugget worth documenting but not sure what exactly.

**Comment by josefs** [comment]
@Zalastax, good idea! I've created an initial page and given you permission to edit. Knock yourself out :-)
