### ISSUE TITLE
function_clause error in typechecker:unary_op_arg_type/2 with --use_beams

### ISSUE THREAD

**Issue by jesperes** [josefs/Gradualizer#360]
Trying to run gradualizer on my "Advent of Code" solutions (https://github.com/jesperes/aoc_erlang) triggered a `function_clause` error when running `rebar3 gradualizer --use_beams`:

```erlang
===> Uncaught error: function_clause
===> Stack trace to the error location:
[{typechecker,unary_op_arg_type,
              ['-',{var,0,"_TyVar-576460752303423391"}],
              [{file,"/home/jespereskilson/dev/aoc_erlang/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,2735}]},
 {typechecker,type_check_unary_op_in,5,
              [{file,"/home/jespereskilson/dev/aoc_erlang/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,2728}]},
 {typechecker,type_check_expr_in,3,
              [{file,"/home/jespereskilson/dev/aoc_erlang/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,2051}]},
 {typechecker,'-type_check_call_ty/4-lc$^0/1-0-',2,
              [{file,"/home/jespereskilson/dev/aoc_erlang/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1864}]},
 {typechecker,'-type_check_call_ty/4-lc$^0/1-0-',2,
              [{file,"/home/jespereskilson/dev/aoc_erlang/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1865}]},
 {typechecker,type_check_call_ty,4,
              [{file,"/home/jespereskilson/dev/aoc_erlang/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1865}]},
 {typechecker,do_type_check_expr,2,
              [{file,"/home/jespereskilson/dev/aoc_erlang/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1434}]},
 {typechecker,type_check_expr,2,
              [{file,"/home/jespereskilson/dev/aoc_erlang/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1311}]}]
```

To reproduce:

* Clone https://github.com/jesperes/aoc_erlang/commit/573a16409e9cf2b29ccb5fdfb809c2da407d845c
* Do `rebar3 gradualizer --use_beams`

Gradualizer version: 0.1.3
Verified on OTP versions: 24.0.6, 23.3.4.2

**Comment by erszcz** [comment]
> The noproc error is probably specific to the rebar3 plugin. My guess is that it doesn't start gradualizer as an OTP application, or something like that which was changed recently in the rest of Gradualizer, except in the rebar3 plugin. (@erszcz makes sense?)

It seems so, indeed.

@jesperes Could you try this branch - https://github.com/erszcz/Gradualizer/tree/start-app-in-rebar-plugin - to check if `noproc` goes away?

**Comment by erszcz** [comment]
Actually, I also added `unary_op_arg_type(_Op, {var, _, _}) -> type(any)` on that branch to check if it fixes the crash.

**Comment by erszcz** [comment]
I think all the stability problems flagged in this ticket are now solved on the master branch:
- `function_clause` in `typechecker,unary_op_arg_type`
- `noproc` of `gradualizer_db`

In other words, we can run Gradualizer on https://github.com/jesperes/aoc_erlang, it will not crash, it will terminate, and it will report warnings, as evidenced by https://gist.github.com/erszcz/4323e97860e67da290f52e2b0998a863.

There are still known correctness issues, i.e. some false positives might be reported - these are a work in progress. I think we can close this ticket. @zuiderkwast @jesperes what do you think?
