### ISSUE TITLE
`remote_type` position handling is incorrect

### ISSUE THREAD

**Issue by erszcz** [josefs/Gradualizer#379]
https://github.com/esl/gradient/issues/31 shows that removing position information leads to `undef, remote_type` being thrown with the position always being equal to 0. This results in warnings like this:

```
Undefined remote type gradualizer_type:abstract_type/0  # when self-gradualizing in the editor
lib/tip_calculator.ex: Undefined remote type Access.get/2 on line 0  # from the issue linked above
```

Having traced the problem I see two things:

```
{trace,<0.93.0>,call,
 {typechecker,normalize_rec,
  [{remote_type,0,
    [{atom,3,'Elixir.Access'},
     {atom,3,get},
     [{atom,0,'Elixir.List'},
      {remote_type,0,[{atom,3,'Elixir.String'},{atom,3,t},[]]}]]},
  ...
```

1. We could use the position from module name or type name (`3` above), which would solve the problem of incorrect line in the warning, BUT...
2. The above means that `typelib:remove_pos` for `remote_type` is actually buggy, since it doesn't remove the position everywhere, so remote type references coming from different source lines do not compare equal :/ I'm not sure if it's a real problem, given we don't see any negative consequences.
3. If we make the `remove_pos` clause for `remote_type` just return the argument type (i.e. not remove the position), we get 11 test failures with a lot of `position_not_removed` errors thrown.

What could we do with this?

It seems that in order to easily compare types we need this information removed, but in order to provide this particular diagnostic we need the position present.

I imagine we could do a first pass before `type_check_forms` to just check for remote types being defined - in this pass the position would not have to be removed. However, that's costly as the entire module would have to be scanned one more time (apart from `erl_lint` and `type_check_forms`).

**Comment by zuiderkwast** [comment]
The location we're reporting in errors is where the error happens in the module being checked. It can be within an expression but in this case it is within a -type or a -spec.

Can we have a separate pass where we check for undefined remote types, user types and records, before we call remove_pos?
