### ISSUE TITLE
Make linting before checking forms optional

### ISSUE THREAD

**Issue by erszcz** [josefs/Gradualizer#382]
When using Gradualizer as a diagnostic provider for external tools (an editor, for example through ErlangLS) it's not necessarily beneficial to prevent running the typechecker if a file being edited doesn't pass linting.

Let's imagine a situation where I stop editing (and e.g. save the file to trigger ErlangLS's diagnostics to run) after removing a parameter from a function definition, but before updating all the call sites. If there were any Gradualizer warnings displayed in the file, they'll suddenly vanish, as the call sites might now call a function which doesn't exist (the arity's changed!), which is a linting error. Due to the linting error the typechecker won't run, so its errors won't be returned. Only after fixing all call sites in the file Gradualizer won't stop on the linting error anymore and start returning previous typechecker errors. This leads to unexpected and confusing flickering of warnings unrelated to the change being made.

Moreover, in case of ErlangLS compiler diagnostics can be configured separately, so it doesn't make sense to get their duplicates from Gradualizer. It makes more sense to call Gradualizer to get the warnings which `erl_lint` cannot provide.

**Comment by zuiderkwast** [comment]
I don't mind that you add it.

The problem though is that you can get all sorts of errors and probably crashes from checking code which contains parse errors.

If you're using Gradualizer as an Erlang library, you can parse the Erlang files separately, do some other checks and then pass the parse tree to `gradualizer:type_check_forms/2` to avoid the linting and also avoid parsing the file multiple times. Does it work for you?

**Comment by erszcz** [comment]
> If you're using Gradualizer as an Erlang library, you [can] pass the parse tree to gradualizer:type_check_forms/2 [...]

Good idea, that might actually be simpler :+1:

> The problem though is that you can get all sorts of errors and probably crashes from checking code which contains parse errors.

Possibly, but I don't think it's going to be that much of a problem. Please have a look at the screenshots below.

Here we have a file that compiles fine - there are warnings about some patterns not matching the types flowing in on lines 25 and 48.

![Screenshot 2022-02-11 at 08 51 50](https://user-images.githubusercontent.com/112145/153555295-fafc82d8-4248-43b6-9ed2-39370bb23631.png)

Here I edited the area around 48, so this form is actually broken - but I haven't saved the file, so Gradualizer didn't run again yet.

![Screenshot 2022-02-11 at 08 52 24](https://user-images.githubusercontent.com/112145/153555318-c937c761-6e57-4159-b3c0-882ef5cc52d1.png)

Here, because `eval1` is now broken we get a new warning about the spec on line 32 - that's fine, since `eval1` is broken. However, why did we lose the warning from line 25? Breaking definition of `eval1` certainly didn't fix the pattern matching in `eval_binding`.

![Screenshot 2022-02-11 at 08 52 40](https://user-images.githubusercontent.com/112145/153555327-d1463f1b-9230-4543-9049-bc57bb755fae.png)

All in all, I think that in case of running checks in the background it makes sense to sidestep linting. Calling directly into `gradualizer:type_check_forms` or even `typechecker:type_check_forms` should do it. Thanks for the feedback!

**Comment by zuiderkwast** [comment]
I do understand the usefulness of this. We can add a `no_lint` option if you want.

> Calling directly into `gradualizer:type_check_forms` or even `typechecker:type_check_forms` should do it.

Yes, but I think the `gradualizer` module is (or should be) the public interface module. The other modules are internal and may be renamed, etc.

I think editors like [ErlIDE](https://erlide.org/) use `syntax_tools` to handle incomplete parse trees with comments, errors and such. Maybe we should have used that format instead of the abstract format....

Another scenario where warnings would disappear is when there are two errors in the same function. Gradualizer stops at the first error in each function. Thus, if a function contains an error and another error is introduced above the first error, the first error would disappear. The reason we abort at the first error is that the remaining errors often are side effects of the first errors and they don't make much sense.

**Comment by erszcz** [comment]
Thanks again! I think the extra option is not necessary :+1:
