### ISSUE TITLE
Not working with mix/elixir

### ISSUE THREAD

**Issue by lukaszsamson** [josefs/Gradualizer#390]
I don't know if mix/elixir support is the goal but Readme mentions gradualixir as a way to run gradualizer with mix. That solution no longer works and the autor doesn't seem to be actively developing gradualixir anymore (see [issue](https://github.com/OvermindDL1/gradualixir/issues/4))

**Comment by zuiderkwast** [comment]
I you figure it out, feel free to remove the references to gradualixir and replace it with a better description on how to use it with Elixir. I don't use Elixir and neither does Josef AFAIK. Maybe @erszcz does?

**Comment by erszcz** [comment]
Indeed, I do. We also work on https://github.com/esl/gradient, which is experimental, but allows to leverage Gradualizer for Elixir codebases. [Gradualixir author admitted he's no longer working on the project](https://elixirforum.com/t/gradualyzer-vs-dialyzer-main-differences/27343/13?u=erszcz), which likely makes Gradient the only alternative.

**Comment by erszcz** [comment]
As of merging #396 the README now points at #esl/gradient. @lukaszsamson do you have any other suggestion on improving the experience for Elixir users? I'll close this for now, but feel free to reopen if there's more to discuss.
