### ISSUE TITLE
Provide a built-in type for record_info

### ISSUE THREAD

**Issue by josefs** [josefs/Gradualizer#40]
The function `record_info/2` is a built-in pseudo-function. Currently, Gradualizer doesn't know about it and reports a type error. We need to add this function to the type environment.

The question is what type we should give this function. There is a whole spectrum of increasingly precise type we could give it. I'm considering whether we should try to make it as precise as possible by actually checking the arguments and return the actual fields or size, depending on how it's called. 

For example, given the following record declaration:
`-record(person, {name, phone, address}).`
The call `record_info(size, person)` would have the singleton type `3`.

**Comment by josefs** [comment]
Commit 0c702abb7ad6c8f510177973f4c45294bbc73350 gives record_info a dynamic type. It silences the Gradualizer from giving erronious type errors. But it's possible to do better.

**Comment by zuiderkwast** [comment]
Closed by #179.
