### ISSUE TITLE
The spec follows a spec with different name/arity

### ISSUE THREAD

**Issue by yordis** [josefs/Gradualizer#421]
I am getting the following issues:

```
commands/accept_address_transfer.ex: The spec new/1 on line 5 follows a spec with different name/arity
commands/accept_address_transfer.ex: The spec put_aggregate_id/2 on line 5 follows a spec with different name/arity
commands/accept_address_transfer.ex: The spec put_aggregate_id/2 on line 5 doesn't match the function name/arity
domain/address_transfer.ex: The spec identifier/0 on line 10 doesn't match the function name/arity
```

Here is the code where it is happening:

```elixir
defmodule AddressTransfers.AcceptAddressTransfer do
  use OnePiece.Commanded.CommandHandler
  use OnePiece.Commanded.Command, aggregate_identifier: :address_transfer_id

  embedded_schema do
    field :accepted_at, :utc_datetime_usec
  end

  # ...
end

defmodule AddressTransfers.AddressTransfer do
  use OnePiece.Commanded.Entity, identifier: :address_transfer_id

  embedded_schema do
  end

  # ....
end
```

I am using the following package to expand the macros: https://github.com/straw-hat-team/beam-monorepo/tree/master/apps/one_piece_commanded/lib/one_piece/commanded

It seems that all the methods added by the macro are not working or something, but I added the typespec correctly (as far as I can tell, my apologies if was something obvious)

**Comment by erszcz** [comment]
Hi, @yordis!

Thanks for the report! This seems like an issue specific to Elixir and therefore [Gradient](https://github.com/esl/gradient) - could you open a ticket there, instead? Sadly, it's not possible to transfer issues between organisations.
