### ISSUE TITLE
Clause cannot be reached on a complex list pattern

### ISSUE THREAD

**Issue by erszcz** [josefs/Gradualizer#423]
The following code:

```erlang
-spec too_complex(list(integer())) -> empty | at_least_one | at_least_two.
too_complex([]) -> empty;
too_complex([_ | _]) -> at_least_one;
too_complex([_, _ | _]) -> at_least_two.
```

Still leads to the following error being reported (at commit 8b4bf33):

```
The clause on line 4 at column 1 cannot be reached
```

This seems like a bug related to `should_list_pat_enable_exhaustiveness_check`.

**Comment by zuiderkwast** [comment]
The type checker is right. The 3rd clause is unreachable.

**Comment by erszcz** [comment]
Ahh, indeed. Too little coffee, I guess :)
