### ISSUE TITLE
function_clause crash in typechecker:do_type_check_expr/2

### ISSUE THREAD

**Issue by jesperes** [josefs/Gradualizer#435]
I get a `function_clause` crash when trying to run Gradualizer (current master `f647ae7`):
```
Error: function_clause
[{lists,nth,[2,[]],[{file,"lists.erl"},{line,198}]},
 {typechecker,do_type_check_expr,2,
              [{file,"/home/jespereskilson/dev/kred/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1747}]},
 {typechecker,type_check_expr,2,
              [{file,"/home/jespereskilson/dev/kred/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,1550}]},
 {typechecker,do_type_check_expr_in,3,
              [{file,"/home/jespereskilson/dev/kred/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,2329}]},
 {typechecker,type_check_expr_in,3,
              [{file,"/home/jespereskilson/dev/kred/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,2320}]},
 {lists,zipwith,3,[{file,"lists.erl"},{line,483}]},
 {lists,zipwith,3,[{file,"lists.erl"},{line,483}]},
 {typechecker,type_check_call,6,
              [{file,"/home/jespereskilson/dev/kred/_build/default/plugins/gradualizer/src/typechecker.erl"},
               {line,3235}]}]
```
OTP version: 25.0.2
Gradualizer: f647ae7 with `--use_beams`

**Comment by erszcz** [comment]
Thanks for the report!
Could you provide a code example on which this happens? Adding `verbose` to `gradualizer_opts` in `rebar.config` like this:

```erlang
{gradualizer_opts, [
  verbose
]}.
```

should enable finding the offending module or even the exact code leading to the above crash (though might generate a lot of output in a big codebase).

Judging from `gradualizer/src/typechecker.erl:1747` it's going to be something with records, possibly partially refined records, i.e. a situation where `-record(r, {field1, ..., fieldN})` and a subsequent `-type r() :: #r{field1 :: type1(), ..., fieldM :: typeM()}` don't match, i.e. `N /= M`.

**Comment by erszcz** [comment]
I think I managed to come up with an example that lead to this error. #436 has a fix for the problem I found. @jesperes it would be great to know if it also solves this issue.

**Comment by erszcz** [comment]
The fix is now merged to master. Please reopen this one or create a new issue if the problem persists.

**Comment by jesperes** [comment]
I am not seeing this any more. Thanks!
