### ISSUE TITLE
Undefined function `module_info/0`

### ISSUE THREAD

**Issue by tsloughter** [josefs/Gradualizer#473]
I can try to dig into this at some point but thought someone would know how gets exported functions for a module? Is it for some reason only getting those exported in the `export` attribute of the module and not builtin ones like in this case:

```
otel_exporter.beam: Call to undefined function grpcbox:module_info/0 on line 73 at column 40
```

**Comment by zuiderkwast** [comment]
Thx for opening the issue. We have some special code for record_info but I guess we haven't added any for module_info yet.

**Comment by xxdavid** [comment]
I've begun to work on this, but it will take me some time as I'm still grokking through the code and my time resources are very limited these days.
