### ISSUE TITLE
Run dialyzer in CI

### ISSUE THREAD

**Issue by Zalastax** [josefs/Gradualizer#60]
@gomoripeti in #53 wrote:

> also could run make dialyze
>
> Im not familiar with the new method and it probably needs to be done by a repo owner but would be nice to integrate travis with github PR checks (https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com)

Would be nice if we follow up on that.

**Comment by josefs** [comment]
Do you mean that we should have travis-ci checking the PRs? That is already happening. I've enabled travis-ci for this repo and I'm seeing the checks passing for the PRs.
