### ISSUE TITLE
Normalization of unary plus

### ISSUE THREAD

**Issue by Zalastax** [josefs/Gradualizer#62]
```
-module(plus).

-spec m(+1) -> {}.
m(+1) ->
    {}.
```

> The pattern + 1 on line 4 doesn't have the type 1

Tying in with #56, it would be nice if I could open a PR which adds this test case as a known bug. Perhaps a `known_problems/should_pass` and `known_problems/should_fail`?

**Comment by josefs** [comment]
I think it'd be excellent to have a `known_problems` directory.
