### ISSUE TITLE
Error loading otp_spec_fix.erl from escript

### ISSUE THREAD

**Issue by gomoripeti** [josefs/Gradualizer#74]
When gradualizer is run as an escript (as on travis) it crashes with the below error:
```
{"init terminating in do_boot",{{badmatch,{error,enotdir}},
[{gradualizer_db,import_erl_files,2,[{file,"/home/travis/build/josefs/Gradualizer/_build/default/lib/gradualizer/src/gradualizer_db.erl"},{line,333}]},
 {gradualizer_db,init,1,[{file,"/home/travis/build/josefs/Gradualizer/_build/default/lib/gradualizer/src/gradualizer_db.erl"},{line,151}]}...
```

This can probably have something to do with `code:priv_dir(gradualizer) => "/home/travis/build/josefs/Gradualizer/gradualizer/gradualizer/priv"` because it is running from an escript archive.

(https://travis-ci.com/josefs/Gradualizer/jobs/156473749)

**Comment by zuiderkwast** [comment]
Oops!

**Comment by zuiderkwast** [comment]
I checked what the escript zip container (using `unzip -l gradualizer`) and it contains no priv dir.

I've tried adding it using escript_incl_extra in the rebar conf as mentioned here http://erlang.2086793.n4.nabble.com/priv-dir-in-escript-td4724193.html but without luck so far.

**Comment by Zalastax** [comment]
It's being looked into! https://github.com/erlang/rebar3/issues/1936

**Comment by zuiderkwast** [comment]
Closing this in favour of #86. Thanks Peter for the idea! It works. (I think you came up with this idea but now I can't find that comment...)

**Comment by zuiderkwast** [comment]
Sorry, reopening. I wanted to close the other PR..
