### ISSUE TITLE
Basic type refinement

### ISSUE THREAD

**Issue by erszcz** [josefs/Gradualizer#91]
Given `getenv/1` from OTP's `os.erl`:

```erlang
-spec getenv(VarName) -> Value | false when
      VarName :: string(),
      Value :: string().

getenv(_) ->
    erlang:nif_error(undef).
```

The following code:

```erlang
-spec get_so_path() -> binary() | string().
get_so_path() ->
    case os:getenv("EJABBERD_SO_PATH") of
        false ->
            case code:priv_dir(mongooseim) of
                {error, _} ->
                    ".";
                Path ->
                    filename:join([Path, "lib"])
            end;
        Path ->
            Path %% this is line 77
    end.
```

Results in:

```
The variable 'Path' on line 77 has type Value | false but is expected to have type binary() | string()
```

Which seems to be incorrect, since the first clause of the `case` rules out `false`, therefore `Path` must be a `string()`. I have a hunch this might be connected with [this comment on type refinements](https://github.com/josefs/Gradualizer/issues/32#issuecomment-424234907), but my understanding of the theory is vague, to say the least :)

Surprisingly, the error persists in this case:

```erlang
-spec get_so_path() -> binary() | string().
get_so_path() ->
    case os:getenv("APP_SO_PATH") of
        false ->
            "/fake/default/path";
        Path ->
            Path
    end.
```

~But disappears when a binary literal is provided in the `false` clause:~
It did disappear due to Vim not being able to parse a Gradualizer crash message.

```erlang
-spec get_so_path() -> binary() | string().
get_so_path() ->
    case os:getenv("APP_SO_PATH") of
        false ->
            <<"/fake/default/path">>;
        Path ->
            Path
    end.
```

**Comment by gomoripeti** [comment]
also related to https://github.com/josefs/Gradualizer/issues/25

your last example is puzzling. The return type of `case` should be the union of the type of the clauses which should still be `binary | ( string() | false )`. weird and good finding.

**Comment by josefs** [comment]
@erszcz, you're right that this problem is related to type refinement. Unfortunately, it might take some time before we get to implement this.

That last example is weird. Feel free to add it to test/known_problems/should_fail/ so we can keep better track of it.

**Comment by erszcz** [comment]
> That last example is weird.

The mystery is solved. I have been tricked by Vim hiding the error indicator, but it did so, cause it couldn't parse a crash report. The problem is gone with 5e1c425510822d0ba0c7e4ef56149c256127c083 and both examples now behave the same.

The title issue, though, remains valid, but as far as I understand it's going to take a while before it gets solved.

**Comment by zuiderkwast** [comment]
The title could be "Basic type refinement" or something similar. That means, excluding an atom in the union type matches the pattern in a previous case/function/catch/receive clause. Doing it in guards is more complex but it can be done in some simple cases as the next step (separate issue).

Actually, I plan to work on this on Wednesday. We have "Hackathon" at work, which means Gradualizer hacking to me. :-)

**Comment by erszcz** [comment]
I'm changing the title accordingly.
